config/routes.rb
Chapter6::Application.routes.draw do
  get "password_resets/new"
  get "password_resets/edit"
  root "static_pages#home"
  get "access/index"
  get "login" => "access#login"
  post "post_login" => "access#attempt_login"
  get 'logout'  => 'access#logout'
  post 'access/attempt_login'
  get "sessions/new"
  get "users/new"
  get "help"    => "static_pages#help"
  get "signup"  => "users#new"
  resources :users do 
    member do 
      get :following, :followers
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets , only: [:new,:create,:edit, :update]
  resources :microposts,       only: [:create, :destroy, :show]
  resources :relationships,    only: [:create, :destroy]

  

end
  

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
	before_action :get_user , only: [:edit, :update]
	before_action :valid_user, only:[:edit, :update]
	def new
	end
	def create
		@user  = User.find_by_email(params['email'])
		if @user
			@user.create_reset_digest
			UserMailer.password_reset(@user).deliver
			flash[:info] = 'Password reset link instructions was sent to your email. Please check!!!'
			redirect_to root_url
		else 
			flash[:danger] = 'Email address not found !!!'
			render :new 
		end
	end
	def edit
	end
	def update
		if params[:user][:password].empty?
			@user.errors.add(:password, "can't be empty")
			render 'edit'
		elsif @user.update_attributes(user_params)
			session[:user_id] = @user.id
			session[:email] = @user.email 
			flash[:success] = "Password has been reset."
			redirect_to user_url(@user.id)
		else
			render 'edit'
		end
	end
  #define private function
  private
  def get_user
  	@user = User.find_by_email(params[:email]) 
  end
  def valid_user
  	unless (@user && @user.activated?)
  		redirect_to root_url
  	end
  end
  def user_params
  	params.require(:user).permit(:password, :password_confirmation)
  end
  # # def check_expiration
  # # 	if @user.password_reset_expired?
  # # 		flash[:danger] = "Password reset has expired."
  # # 		redirect_to new_password_reset_url
  # # 	end
  # end
end

app/helpers/password_resets_helper.rb
module PasswordResetsHelper
end

app/views/password_resets/edit.html.erb
<% content_for :title do %>
<title>Reset Password</title>
<% end %>
<%= content_for :page_title do %>
Reset Password
<% end %>
<%= form_for(@user, url: password_reset_path(params[:id])) do |f| %>
<%= render 'shared/error_messages' , object: f.object %>

<%= hidden_field_tag :email, @user.email %>

<%= f.label :password %>
<%= f.password_field :password, class: 'form-control' %>

<%= f.label :password_confirmation, "Confirmation" %>
<%= f.password_field :password_confirmation, class: 'form-control' %>

<%= f.submit "Update password", class: "btn btn-primary" %>
<% end %>

app/views/password_resets/new.html.erb
<% content_for :title do %>
<title>Reset Password</title>
<% end %>
<%= content_for :page_title do %>
Send Reset Link
<% end %>
<%= form_tag(action: 'create') do %>
<%= label_tag(:email) %>
<%= email_field_tag(:email,nil, class: 'form-control') %>
<br/><br/>
<%= submit_tag("Login",class: 'form-control btn btn-primary') %>
<% end %>