config/routes.rb
Chapter6::Application.routes.draw do
  get "password_resets/new"
  get "password_resets/edit"
  root "static_pages#home"
  get "access/index"
  get "login" => "access#login"
  post "post_login" => "access#attempt_login"
  get 'logout'  => 'access#logout'
  post 'access/attempt_login'
  get "sessions/new"
  get "users/new"
  get "help"    => "static_pages#help"
  get "signup"  => "users#new"
  resources :users do 
    member do 
      get :following, :followers
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets , only: [:new,:create,:edit, :update]
  resources :microposts,       only: [:create, :destroy, :show]
  resources :relationships,    only: [:create, :destroy]

  

end
  

app/views/layouts/_follow.html.erb
<%= form_for(current_user.active_relationships.build) do |f| %>
  <div><%= hidden_field_tag :followed_id, @user.id %></div>
  <%= f.submit "Follow", class: "btn btn-primary" %>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="footer" style="background: #DBDBDB; height: 100px; border-top : 5px solid #00BDFF; position: fixed; bottom: 0px; width:100%" >
  <h3 class="text-center">
    Trung Manucian | Framgia 2016
  </h3>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to t("branch"), root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home",   root_path %></li>
        <li><%= link_to "Help",   help_path %></li>
        <li><%= link_to "Users",   users_path %></li>
        <% if !current_user.blank? %>
        <li><%= link_to "Posts" , user_path(current_user) %></li> 
        <% end %>
        <% if current_user.blank?%>
        <li><%= link_to "Sign up", signup_path %></li>
        <li><%= link_to "Log in", login_path %></li>
        <% end %>
        <% if !current_user.blank? %>
        <li class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown" href="#"><%= current_user.name %>
            <span class="caret"></span></a>
            <ul class="dropdown-menu">

              <li><%= link_to "Logout" , logout_path %></li> 
            </ul>
          </li>
          <% end %>
        </ul>
      </nav>
    </div>
  </header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/_unfollow.html.erb
<%= form_for(current_user.active_relationships.find_by(followed_id: @user.id),
             html: { method: :delete }) do |f| %>
  <%= f.submit "Unfollow", class: "btn" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<%= yield :title %>
	<%= stylesheet_link_tag 'application', media: 'all',
	'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	<%= csrf_meta_tags %>
	<%= render 'layouts/shim' %>
	<script>
		
			$(document).ready(function(){
			   $('.alert').delay(1000).slideUp()	
			})
			
	</script>
</head>
<body> 
	<div class="wrapper"  style="min-height: 800px">
		<%= render 'layouts/header' %>

		<div class="container" style="margin-bottom: 100px">
			<div class="row">
				<div class="col-md-10 col-md-offset-1">
					<h1><%= yield :page_title %></h1>
					<% flash.each do |message_type, message| %>
					<div class="alert alert-<%= message_type %>"><%= message %></div>
					<% end %>
					<hr />
					<%= yield %>
				</div>
				
			</div>

		</div>	
		<%= render 'layouts/footer' %>
	</div>		
	
</body>
</html>